"""
Core data models shared by all pipeline stages.

Data flows through the pipeline in two forms:
  RawJob   → output of any scraper; fields are normalized but not scored
  ScoredJob → output of the Scorer; inherits all RawJob fields and adds score data

CompanyConfig and DisqualifyResult are auxiliary models used by the orchestrator
and the Disqualifier respectively.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, field_validator


class RawJob(BaseModel):
    """
    A job posting as received from any scraper, after normalization.

    The URL field is automatically cleaned on construction (tracking params stripped)
    so that the same job fetched from different sources produces the same dedup key.
    """
    id:               str               # e.g. "greenhouse:12345"
    title:            str
    company:          str
    url:              str               # normalized — see field_validator below
    location_raw:     Optional[str] = None
    posted_date:      Optional[datetime] = None
    description_html: str = ""          # raw HTML from the ATS, not yet stripped
    source:           str               # greenhouse | lever | smartrecruiters | workday | custom
    raw_payload:      dict = {}         # the original API response, for debugging
    detected_language: Optional[str] = None
    translated:       bool = False

    @field_validator("url")
    @classmethod
    def normalize_url(cls, v: str) -> str:
        """
        Strip common tracking query parameters from the job URL.

        ATS platforms (especially Greenhouse) append parameters like `gh_src`,
        `utm_source`, etc. that change per-click but don't identify a unique job.
        Stripping them ensures that:
          1. Deduplication against Google Sheets works correctly across runs.
          2. The stored URL is clean for the user to click on.
        """
        from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

        parsed   = urlparse(v)
        tracking = {"utm_source", "utm_medium", "utm_campaign", "src", "ref", "token", "gh_src"}
        qs       = {k: vals for k, vals in parse_qs(parsed.query).items() if k not in tracking}
        clean    = parsed._replace(query=urlencode(qs, doseq=True))
        return urlunparse(clean).rstrip("/")

    def dedup_key(self) -> str:
        """Primary deduplication key. Normalized URL is stable across scraper runs."""
        return self.url


class ScoredJob(RawJob):
    """
    A RawJob enriched with scoring results and an optional cover letter.

    Created by pipeline/scorer.py. Inherits all RawJob fields so it can be passed
    anywhere a RawJob is expected (e.g. google_sheets.py).
    """
    score:            float = 0.0
    # Breakdown of the five scoring dimensions + detail dicts from each dimension.
    # Example: {"title": 22.5, "tech_stack": 20.0, ..., "title_best_match": "data scientist"}
    score_breakdown:  dict = {}
    cover_letter:     Optional[str] = None    # generated by cover_letter.py when requested
    work_type:        Optional[str] = None    # hybrid | on-site | remote | unknown
    requirements_text: str = ""               # LLM-extracted or heuristically parsed requirements
    tech_stack_found: list[str] = []          # skill names matched in the description
    date_added:       Optional[datetime] = None


class CompanyConfig(BaseModel):
    """One entry from config/companies.yaml."""
    name:       str
    ats:        str               # greenhouse | lever | smartrecruiters | workday | custom
    slug:       Optional[str] = None      # used by API-based scrapers (Greenhouse, Lever)
    career_url: Optional[str] = None      # used by Playwright-based scrapers (Workday, custom)
    enabled:    bool = True
    notes:      Optional[str] = None


class DisqualifyResult(BaseModel):
    """Return value of Disqualifier.check(). Carries the reason for easier debugging."""
    is_disqualified: bool
    reason:          Optional[str] = None
